function(LINK_FRAMEWORK libs_dir library_name)
    file(GLOB FRAMEWORKS "${libs_dir}/*.xcframework")
    if (FRAMEWORKS STREQUAL "")
        file(GLOB FRAMEWORKS "${libs_dir}/*.framework")
    endif ()
    if (FRAMEWORKS STREQUAL "")
        message(FATAL_ERROR "FRAMEWORKS is empty")
    else ()
        message(STATUS "FRAMEWORKS " ${FRAMEWORKS})
    endif ()
    foreach (framework ${FRAMEWORKS})
        get_filename_component(FRAMEWORK ${framework} NAME_WE)
        if (IS_DIRECTORY "${libs_dir}/${FRAMEWORK}.xcframework")
            if (IRIS_PLUGIN_PLATFORM STREQUAL "Mac")
                set(LIBS_DIR "${libs_dir}/${FRAMEWORK}.xcframework/macos-arm64_x86_64")
            else ()
                if (PLATFORM MATCHES "^SIMULATOR.*$")
                    set(LIBS_DIR "${libs_dir}/${FRAMEWORK}.xcframework/ios-arm64_x86_64-simulator")
                else ()
                    set(LIBS_DIR "${libs_dir}/${FRAMEWORK}.xcframework/ios-arm64_armv7")
                endif ()
            endif ()
        else ()
            set(LIBS_DIR "${libs_dir}")
        endif ()
        if (FRAMEWORK MATCHES "^.*Extension$")
            message(STATUS "FRAMEWORK " ${FRAMEWORK})
            get_target_property(LINK_FLAGS ${library_name} LINK_FLAGS)
            set_target_properties(${library_name} PROPERTIES
                    LINK_FLAGS "${LINK_FLAGS} -F ${LIBS_DIR}"
                    )
            target_link_libraries(${library_name}
                    PRIVATE
                    "-weak_framework ${FRAMEWORK}"
                    )
        endif ()
    endforeach ()
endfunction()
